// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGDuZyM_43m6IRKC0JcI4y3IPwkp6ZAJk',
    appId: '1:341887486568:web:0f3ee9809ef743980549dd',
    messagingSenderId: '341887486568',
    projectId: 'desvendando-a-odontologia',
    authDomain: 'desvendando-a-odontologia.firebaseapp.com',
    storageBucket: 'desvendando-a-odontologia.firebasestorage.app',
    measurementId: 'G-TTMPWRF7YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR_-j__novoF0YYiI5rJYq0f0O1XHkjkk',
    appId: '1:341887486568:android:aa90728ec87602f70549dd',
    messagingSenderId: '341887486568',
    projectId: 'desvendando-a-odontologia',
    storageBucket: 'desvendando-a-odontologia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk6JjINIYy8oSy5rHIx2llc2bMpf6M7CU',
    appId: '1:341887486568:ios:966f901081925eab0549dd',
    messagingSenderId: '341887486568',
    projectId: 'desvendando-a-odontologia',
    storageBucket: 'desvendando-a-odontologia.firebasestorage.app',
    iosBundleId: 'com.example.desvendandoAOdontologia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk6JjINIYy8oSy5rHIx2llc2bMpf6M7CU',
    appId: '1:341887486568:ios:966f901081925eab0549dd',
    messagingSenderId: '341887486568',
    projectId: 'desvendando-a-odontologia',
    storageBucket: 'desvendando-a-odontologia.firebasestorage.app',
    iosBundleId: 'com.example.desvendandoAOdontologia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGDuZyM_43m6IRKC0JcI4y3IPwkp6ZAJk',
    appId: '1:341887486568:web:4e91d1b7f61372b40549dd',
    messagingSenderId: '341887486568',
    projectId: 'desvendando-a-odontologia',
    authDomain: 'desvendando-a-odontologia.firebaseapp.com',
    storageBucket: 'desvendando-a-odontologia.firebasestorage.app',
    measurementId: 'G-S6F9YZ1QTH',
  );
}
